#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # get tweets
    tweets = helpers.get_user_timeline(sys.argv[1], 50)

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze tweets
    if tweets == None:
        exit(1)
    else:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(score, "green"), end="")
                print(" " + tweet)
            elif score < 0.0:
                print(colored(score, "red"), end="")
                print(" " + tweet)
            else:
                print(colored(score, "yellow"), end="")
                print(" " + tweet)

if __name__ == "__main__":
    main()